### ISSUE TITLE
Docker compose with Mongo

### ISSUE THREAD

**Issue by AntoineMilliot** [adaltas/ece-devops-2022-fall#8]
When I run 
```
docker-compose up
```
The server start properly but the mongo connection does not, I have a message error
```
 connect ECONNREFUSED 127.0.0.1:27017
```
I do not find any solution on internet

**Comment by Eagles27** [comment]
Hi @AntoineMilliot 👋🏼 

You should white List **all ip's addresses** on mongo Atlas or just authorize some Ip's as you want. 
To do that you have to change some settings into Network Access on mongo Atlas, look at the picture just below. 

I hope it helped you ! 😉 

![image](https://user-images.githubusercontent.com/92862523/209682808-25fa0cc8-29db-4ff6-92b4-eea3932a3f51.png)
